// Mocks generated by Mockito 5.4.6 from annotations
// in fintrack/test/presentation/bloc/transaction_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fintrack/domain/entities/transaction.dart' as _i4;
import 'package:fintrack/domain/usecases/add_transaction.dart' as _i5;
import 'package:fintrack/domain/usecases/delete_transaction.dart' as _i6;
import 'package:fintrack/domain/usecases/get_balance.dart' as _i7;
import 'package:fintrack/domain/usecases/get_transactions.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GetTransactions].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTransactions extends _i1.Mock implements _i2.GetTransactions {
  MockGetTransactions() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Transaction>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i3.Future<List<_i4.Transaction>>.value(
              <_i4.Transaction>[],
            ),
          )
          as _i3.Future<List<_i4.Transaction>>);
}

/// A class which mocks [AddTransaction].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddTransaction extends _i1.Mock implements _i5.AddTransaction {
  MockAddTransaction() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call(_i4.Transaction? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#call, [transaction]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [DeleteTransaction].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteTransaction extends _i1.Mock implements _i6.DeleteTransaction {
  MockDeleteTransaction() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#call, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [GetBalance].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetBalance extends _i1.Mock implements _i7.GetBalance {
  MockGetBalance() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<double> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i3.Future<double>.value(0.0),
          )
          as _i3.Future<double>);
}
